---
# control

control: 
  data_name: MNIST
  model_name: linear
  regularizer_name : none 
  lambda : 0.0
  reg_optimizer : SGD 
  reg_initialization : inplace 
  clipping_scale : 1.0 
  line_crossing : False
  p : 1.0 
  q : 2.0 

seed : 0

resume_mode: 0
device: cuda
verbose: False

# Regularization


# experiment
# pin_memory: True
# num_workers: 0
# log_interval: 0.25
# world_size: 1

