---
# control

data_name: MNIST
model_name: linear

init_seed: 0

num_experiments: 1
resume_mode: 0
device: cuda
verbose: False

# experiment
# pin_memory: True
# num_workers: 0
# log_interval: 0.25
# world_size: 1

